apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-deployment
  name: python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: python-deployment
    spec:
      containers:
      - name: python-deployment
        image: gcr.io/focused-bridge-317713/python-img:v3.0
        ports:
         - containerPort: 8000
      - name: redis
        image: redis
        ports:
        - containerPort: 6379